Use RuntimeException in JavascriptException
chrome-php/headless-chromium-php pull request #526
Opened 2023-05-26 20:49 UTC by buismaarten

Hey there,

I want to semantically separate the exceptions that can be thrown by this package.
When the JavascriptException is thrown it means something happened during the execution of the given JavaScript code. If JavascriptException extends RuntimeException it can be caught by the same try-catch statement to catch other application specific errors.

JavascriptException extends the Exception class at the moment, RuntimeException also extends the Exception class. Hereby there are no breaking changes.

Hey there,

I want to semantically separate the exceptions that can be thrown by this package.

When the JavascriptException is thrown, it means that something happened during the execution of the given JavaScript code. If JavascriptException extends RuntimeException, it can be caught by the same try-catch statement to catch other application-specific errors.

JavascriptException currently extends the Exception class, RuntimeException also extends the Exception class. No breaking changes here.

2023-05-27 13:25 UTC, GrahamCampbell requested changes
If we do this, we'd also need to remove `JavascriptException` from all throws blocks. Every PHP method already has an implicit throws `RuntimeException|Error`. That is, throws doc is only for documenting non-runtime exceptions and non-errors.

2023-05-27 14:17 UTC, buismaarten commented
Made some changes, hopefully I made the right changes!

2023-05-31 21:54 UTC, buismaarten commented
@GrahamCampbell ping

2023-05-31 21:58 UTC, GrahamCampbell commented
I think this is probably a breaking change, so this may need to wait till 2.x.

2023-05-31 21:58 UTC, GrahamCampbell commented
Breaking because someone catching `RuntimeException` now catches this when they weren't expecting to.

2023-05-31 22:15 UTC, closed without merging