fix precision loss (int vs float mixup)
chrome-php/headless-chromium-php pull request #655
Opened 2024-10-25 07:29 UTC by divinity76

The origin X/Y comes from Page.getLayoutMetrics.cssContentSize which returns float values like -0.666748046875 , not integers, but the library erroneously treated it like integers, that can cause Mouse()->click to miss-click on very small targets, and with custom error handlers it can also cause
```
["trace":"Exception":private]=>
    array(9) {
      [0]=>
      array(4) {
        ["file"]=>
        string(52) "C:\temp\vendor\chrome-php\chrome\src\Input\Mouse.php"
        ["line"]=>
        int(338)
        ["function"]=>
        string(9) "{closure}"
        ["args"]=>
        array(4) {
          [0]=>
          int(8192)
          [1]=>
          string(69) "Implicit conversion from float -0.666748046875 to int loses precision"
          [2]=>
          string(52) "C:\temp\vendor\chrome-php\chrome\src\Input\Mouse.php"
          [3]=>
          int(338)
        }
      }
```

2024-10-25 07:44 UTC, divinity76 commented
is it possible that float scroll position is a recent change in chrome itself? seems much of the code is written with the expectation that scroll position is int, not float 🤔 but window.scrollY is float (and very floaty like X.5), not int

2024-10-25 07:47 UTC, divinity76 commented
fixing this actually requires breaking the public api a little bit: $page->mouse()->getPosition() 
used to return `array(int, int);`  but when fixing this it returns `array(float, float)` 🤔

2024-10-29 20:01 UTC, enricodias commented
This would change the public api, although changing to float shouldn't be a breaking change and old implementations using integers should still work 🤔

But if those tests shouldn't fail.

2025-05-28 18:58 UTC, divinity76 commented
@enricodias fixed the testcases. (some were expecting int but getting float. no failures beyond that)

2025-05-28 20:55 UTC, enricodias approved these changes

2025-05-28 21:09 UTC, GrahamCampbell requested changes

2025-05-28 21:09 UTC, GrahamCampbell commented on src/Input/Mouse.php
> +    public function move(float $x, float $y, ?array $options = null)
This is a breaking change, when the caller has strict types enabled.

2025-05-28 22:08 UTC, divinity76 commented on src/Input/Mouse.php
> +    public function move(float $x, float $y, ?array $options = null)
commented on wrong line, but yes. the actual api break is on line 34, 35 and 338. 
strict_types have an exception for implicit int->float, so line 57 is not an api break: https://3v4l.org/gS1b7
thus function move can be upgraded to support float without breaking api,
but function getPosition() and getMaximumDistance() cannot. 

Would you prefer to only fix the
>Implicit conversion from float -0.666748046875 to int loses precision

issue, at least for the remainder of v1?

2025-05-29 04:14 UTC, enricodias commented on src/Input/Mouse.php
> +    public function move(float $x, float $y, ?array $options = null)
Why is `getMaximumDistance` a breaking change if it's a private method? And `getPosition` returns an array with no defined types, not even in the docblock.

2025-05-30 13:21 UTC, divinity76 commented on src/Input/Mouse.php
> +    public function move(float $x, float $y, ?array $options = null)
@enricodias 
> Why is `getMaximumDistance` a breaking change if it's a private method?

sorry you're right, getMaximumDistance is not a breaking change, my bad.

>And getPosition returns an array with no defined types, not even in the docblock.

that's kinda a api-break because code that expect `$page->mouse()->getPosition()['y']` to be int may be disappointed. (it broke tests/MouseApiTest.php line 85 test case)

IMO it's a minor API break tho. ["x"=>int,"y"=>int] becomes ["x"=>float,"y"=>float].

2026-02-04 00:01 UTC, closed without merging